### ISSUE TITLE
[typescript] `Identify` type is being used in the index.ts but it's undefined

### ISSUE THREAD

**Issue by tsekityam** [rudderlabs/rudder-typer#161]
I use `pnpx rudder-typer init` to generate `index.ts` for my tracking plan. In the ts file, there are ref to `Identify` in several locations, e.g. `identify()`.

```
import type {
  RudderAnalytics,
  RudderAnalyticsPreloader,
  ApiOptions,
  ApiObject,
} from '@rudderstack/analytics-js'

\\ skips

export function identify(
  userIdOrTraits?: string | Identify,
  traitsOrOptions?: Record<string, any> | ApiOptions,
  optionsOrCallback?: ApiOptions | apiCallback,
  callback?: apiCallback
): void {
  const a = analytics()

  if (a) {
    const userId =
      typeof userIdOrTraits === 'string' ? userIdOrTraits : undefined
    const traits =
      typeof userIdOrTraits === 'string'
        ? (traitsOrOptions as Identify)
        : (userIdOrTraits as Identify)
    const options =
      typeof userIdOrTraits === 'string'
        ? (optionsOrCallback as ApiOptions)
        : (traitsOrOptions as ApiOptions)
    const cb =
      typeof userIdOrTraits === 'string'
        ? callback
        : (optionsOrCallback as apiCallback)

    a.identify(userId, traits || {}, withRudderTyperContext(options), cb)
  }
}


// skips
```

However, the `Identify` type is never being import nor defined. There are only 3 use of the type

<img width="545" alt="Image" src="https://github.com/user-attachments/assets/380bc164-87e8-47b1-985c-78139246f979" />

and I got the following error

```
Cannot find name 'Identify'.
```

**Comment by akashrpo** [comment]
Hi @tsekityam,
This issue has been resolved in the latest version of RudderTyper. Please upgrade to v1.6.1 and regenerate your bindings:

or use 
```
npx rudder-typer@latest init
```

**Comment by tsekityam** [comment]
Hi @akashrpo, I tried `npx rudder-typer@latest init`, then I got an unknown error. And here is what I did

```
$ nvm use --lts
$ npx rudder-typer@latest init

>   RudderTyper is a tool for generating strongly-typed RudderStack analytics 
>   libraries based on a Tracking Plan.
> 
>   To get started, you'll need a ruddertyper.yml file. The quickstart guide below 
>   will walk you through the process of creating one.
> 
> 
> 
> 
>   Ready?
>    → Hit return to continue.
> 
>    ❯ Ok!

> Choose a SDK:                                                              [1/7]
>    → Use the arrow keys to navigate.
>    → RudderTyper clients are strongly-typed wrappers for the RudderStack SDK.
>    → To learn more about the RudderStack SDKs, visit the documentation.
> 
>    ❯ Web (analytics.js)
>      Node.js (analytics-node)
>      iOS (analytics-ios)
>      Android (analytics-android)

>   Choose a language:                                                         [2/7]
> 
>      JavaScript
>    ❯ TypeScript

>   ✘ Error: 
> 
>   If you are unable to resolve this issue,open an issue on GitHub. Please include 
>   that you are using version 1.6.1 of RudderTyper.
> 
```

**Comment by tsekityam** [comment]
Hi @akashrpo, The index.ts generated still has 3 `Identify` in the same location, and it is still not being imported nor defined in the file. So the error still there.

Here is the version that I use 
```
kityamtse@MacBookPro js % node --version
v22.14.0
kityamtse@MacBookPro js % npx rudder-typer@latest version
Version: 1.6.1
```

**Comment by akashrpo** [comment]
Hi @tsekityam, are we applying Identify rules to properties in the Tracking Plan UI, or are we focusing on traits or context.traits?

**Comment by tsekityam** [comment]
Hi @akashrpo , here is my tracking plan setting. 

<img width="998" alt="Image" src="https://github.com/user-attachments/assets/ddcae91a-fc0c-4e99-bf37-4477fd0db73f" />
